### ISSUE TITLE
too much Swift Compiler Warning

### ISSUE THREAD

**Issue by StevenArmandLee** [NetcoreSolutions/Netcore-iOS-SDK#3]
there are a lot of warnings coming from this. most of them is Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)

coming from NetCorePushTaskManager.h

**Comment by icodebuster** [comment]
@StevenArmandLee 
We will be fixing the warning in the next release, thank you for the heads up.

**Comment by icodebuster** [comment]
@StevenArmandLee All the warnings are fixed in v2.3.8. Request you to update the same.
