### ISSUE TITLE
UIWebView Deprecation Warning

### ISSUE THREAD

**Issue by momoohidayat** [NetcoreSolutions/Netcore-iOS-SDK#4]
Hi NetcoreSolutions Team,

I want to ask about UIWebView deprecation warning when i upload my build to testflight after i integrate netcore into my project.

To make sure, i never use UIWebView inside my whole project, and from previous build (before i integrate netcore) there's no single warning from apple about using UIWebView on my build.

i use cocoapods, with Netcore SDK version 2.4.1

Can you please check if this warning because of Netcore iOS SDK?

Warm regards,

**Comment by momoohidayat** [comment]
```
NetCorePush
         U _OBJC_CLASS_$_UIWebView
                 U _OBJC_CLASS_$_UIWebView
```

i use this method to check on my build:
https://stackoverflow.com/a/57730461

**Comment by icodebuster** [comment]
@momoohidayat 
We are using UIWebViews to render the InApp Messages. The team is working on getting this fixed in the up coming releases and migrate to WKWebViews.

**Comment by momoohidayat** [comment]
@icodebuster do you know when can we expect the next release?

**Comment by icodebuster** [comment]
@momoohidayat Tentatively in March. Currently, there is 1 release under QA post which we will be working the above-said issue.

**Comment by momoohidayat** [comment]
Hi @icodebuster any update/info about this issue?

**Comment by momoohidayat** [comment]
Hi @icodebuster how about this issue? any ETA for the release?

**Comment by icodebuster** [comment]
@momoohidayat We have release a new SDK v2.4.3 which is now using WKWebView.
